### ISSUE TITLE
[iOS] Does not work on physical device (arm64)

### ISSUE THREAD

**Issue by matmork** [matmork/rive-maui#5]
Running on a physical device in iOS results in crash.

```
Exception Type:  EXC_BAD_ACCESS (SIGKILL)
Exception Subtype: KERN_INVALID_ADDRESS at 0x80000003002d12c0 -> 0x00000003002d12c0 (possible pointer authentication failure)
```

Will investigate...

**Comment by hansmbakker** [comment]
Probably this is not related? https://github.com/rive-app/rive-ios/issues/287

**Comment by matmork** [comment]
Got it working by calling the Objective-C directly and not via the swift wrapper.  Will probably work when [Swift Interop](https://github.com/dotnet/designs/blob/main/proposed/swift-interop.md) is available (maybe .NET 9). Meanwhile this solution seems to be working, just requires some more code.

**Comment by hansmbakker** [comment]
The tracking issue for that is https://github.com/dotnet/runtime/issues/93631 - maybe it can be added as a reference or link somehow.
