### ISSUE TITLE
Nuget push workflow failed

### ISSUE THREAD

**Issue by hansmbakker** [matmork/rive-maui#8]
I saw the `nuget-push.yml` workflow [failed](https://github.com/matmork/rive-maui/actions/runs/8711036372), I restarted it with debug logging to check what's wrong.

I used `View raw logs` in the mobile web interface but couldn't gather more info there:
![image](https://github.com/matmork/rive-maui/assets/3463496/0f6cd628-b056-45fc-bb3d-5487d78bbc09)

Exactly the same command is run in `ci-build.yml`, the only difference is the `Release` vs `Debug` configuration.

Does the command below work for you locally after running `dotnet clean` and after creating an empty `staging` folder?

> dotnet pack -o staging -c Release src/Rive.Android/Rive.Android.csproj look

**Comment by matmork** [comment]
Pretty sure this is because `<GeneratePackageOnBuild>true</GeneratePackageOnBuild>`
Seems to work without, but can't get the prefix part to work see [nuget-build](https://github.com/matmork/rive-maui/commit/c3792777602662c8677b17a785fb603066978658) branch

**Comment by hansmbakker** [comment]
Oh! Actually in the `nuget-push` pipeline the suffix should not be needed (unless you intend to push to nuget with suffixes).
It's mostly useful for PR builds (this is why it is in the `ci-build` pipeline).

**Comment by matmork** [comment]
Just testing, reverted the changes to nuget-push. The PR builds did not show the prefix. Changing to `<VersionPrefix>` instead of `<Version>` seems to do the trick

**Comment by hansmbakker** [comment]
@matmork I pressed "submit feedback" on my phone intending to send my comments, but that immediately caused it to merge (I expected that it would merge only when I clicked "approve" 🤦🏼‍♂️).

Anyway - the comments were questions - feel free to have a look at them, and I'm curious about your thoughts.

**Comment by hansmbakker** [comment]
Also: I see that the publish (nuget push) step failed now.

Two things to check:
- Maybe nuget push doesn't support uploading multiple files at once, and then we have to do something similar to the earlier step
- did you correctly put the API key in the GitHub repository secrets?

**Comment by matmork** [comment]
> Also: I see that the publish (nuget push) step failed now.
> 
> Two things to check:
> 
> * Maybe nuget push doesn't support uploading multiple files at once, and then we have to do something similar to the earlier step
> * did you correctly put the API key in the GitHub repository secrets?

Yes the secret is added. It should work with multiple files. Not sure what's going on. Maybe try `dotnet nuget push` instead of just `nuget push`? 

https://stackoverflow.com/questions/65507487/push-multiple-nupkg-files-to-github-packages-using-powershell

**Comment by hansmbakker** [comment]
> Maybe try dotnet nuget push instead of just nuget push?

It looked good to me as it was but `dotnet nuget push` could also be worth a try!

**Comment by hansmbakker** [comment]
One thing though - are we sure that the workflow has access to the secret?
